2020-11-08 14:16:04,049 INFO    MainThread:22596 [internal.py:wandb_internal():63] W&B internal server running at pid: 22596
2020-11-08 14:16:04,051 DEBUG   HandlerThread:22596 [handler.py:handle_request():55] handle_request: check_version
2020-11-08 14:16:04,051 INFO    WriterThread:22596 [datastore.py:open_for_write():76] open: wandb\run-20201108_141603-2vl3irn6\run-2vl3irn6.wandb
2020-11-08 14:16:04,052 DEBUG   SenderThread:22596 [sender.py:send():90] send: header
2020-11-08 14:16:04,052 DEBUG   SenderThread:22596 [sender.py:send():90] send: request
2020-11-08 14:16:04,052 DEBUG   SenderThread:22596 [sender.py:send_request():99] send_request: check_version
2020-11-08 14:16:04,059 DEBUG   Thread-8  :22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): pypi.org:443
2020-11-08 14:16:04,121 DEBUG   Thread-8  :22596 [connectionpool.py:_make_request():433] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51383
2020-11-08 14:16:04,158 DEBUG   SenderThread:22596 [sender.py:send():90] send: run
2020-11-08 14:16:04,159 INFO    SenderThread:22596 [sender.py:_maybe_setup_resume():280] checking resume status for None/ch-en-try/2vl3irn6
2020-11-08 14:16:04,161 DEBUG   SenderThread:22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:16:04,304 DEBUG   SenderThread:22596 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:16:04,311 DEBUG   SenderThread:22596 [util.py:is_cygwin_git():315] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2020-11-08 14:16:04,318 DEBUG   SenderThread:22596 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:16:04,379 DEBUG   SenderThread:22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:16:04,514 DEBUG   SenderThread:22596 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:16:04,548 DEBUG   HandlerThread:22596 [handler.py:handle_request():55] handle_request: run_start
2020-11-08 14:16:04,556 INFO    SenderThread:22596 [dir_watcher.py:__init__():164] watching files in: wandb\run-20201108_141603-2vl3irn6\files
2020-11-08 14:16:04,556 INFO    SenderThread:22596 [sender.py:_start_run_threads():487] run started: 2vl3irn6 with start time 1604862963
2020-11-08 14:16:04,556 DEBUG   SenderThread:22596 [sender.py:send():90] send: summary
2020-11-08 14:16:04,556 INFO    SenderThread:22596 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2020-11-08 14:16:04,584 DEBUG   HandlerThread:22596 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:16:04,638 DEBUG   HandlerThread:22596 [cmd.py:execute():718] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=None)
2020-11-08 14:16:04,793 DEBUG   HandlerThread:22596 [handler.py:handle_request():55] handle_request: status
2020-11-08 14:16:04,793 DEBUG   SenderThread:22596 [sender.py:send():90] send: files
2020-11-08 14:16:04,793 INFO    SenderThread:22596 [sender.py:_save_file():568] saving file wandb-metadata.json with policy now
2020-11-08 14:16:04,796 DEBUG   SenderThread:22596 [sender.py:send():90] send: request
2020-11-08 14:16:04,797 DEBUG   SenderThread:22596 [sender.py:send_request():99] send_request: status
2020-11-08 14:16:04,799 DEBUG   SenderThread:22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:16:04,804 DEBUG   Thread-17 :22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:16:04,835 DEBUG   HandlerThread:22596 [handler.py:handle_request():55] handle_request: pause
2020-11-08 14:16:04,836 INFO    HandlerThread:22596 [handler.py:handle_request_pause():226] stopping system metrics thread
2020-11-08 14:16:04,895 DEBUG   SenderThread:22596 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:16:04,897 DEBUG   SenderThread:22596 [sender.py:send():90] send: config
2020-11-08 14:16:04,901 DEBUG   SenderThread:22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:16:04,963 DEBUG   Thread-17 :22596 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:16:04,967 DEBUG   Thread-17 :22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-08 14:16:05,073 DEBUG   SenderThread:22596 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:16:05,250 DEBUG   Thread-17 :22596 [connectionpool.py:_make_request():433] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/submalpast/ch-en-try/2vl3irn6/wandb-metadata.json?Expires=1604949365&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=X97HHWDVIkqvu7PVBHlwG3vy%2B6wm4pheYlmf%2BBP08pqrbKs2ULxm%2FRDDp%2F%2FM4ueYHhPhj5SgRnH2FbsWMWBIDxByPMCGN2OjjlWDcoFSRjYy2hI%2FZ8SL9iZsjwJgWqGgMEpihEokXq8U%2FxomLs8didMCVE%2FvZo2VROoGgwHS734FXvE2vZgyOMyoVnWWJ6%2FuG6risQU2gnrgL%2F8BriODwkwBADiHYCvRue085qhVWKOIqFtbAhcAxu9rV9EDohVaSepk3Et9N0MXeBMd4fRuVdZKybpZIJrafjw0TJeBVCMQomO%2FZtgpVTdKfclygOkg5cJv44EZ6HuUxTiZgKnFEw%3D%3D HTTP/1.1" 200 0
2020-11-08 14:16:05,254 INFO    Thread-17 :22596 [upload_job.py:push():131] Uploaded file C:\Users\presu\AppData\Local\Temp\tmpkuysj_x0wandb\o64frdse-wandb-metadata.json
2020-11-08 14:16:05,559 INFO    Thread-12 :22596 [dir_watcher.py:_on_file_modified():225] file/dir modified: wandb\run-20201108_141603-2vl3irn6\files\config.yaml
2020-11-08 14:16:05,560 INFO    Thread-12 :22596 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_141603-2vl3irn6\files\requirements.txt
2020-11-08 14:16:05,560 INFO    Thread-12 :22596 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_141603-2vl3irn6\files\wandb-metadata.json
2020-11-08 14:16:05,560 INFO    Thread-12 :22596 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_141603-2vl3irn6\files\output.log
2020-11-08 14:16:05,560 INFO    Thread-12 :22596 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_141603-2vl3irn6\files\wandb-summary.json
2020-11-08 14:16:05,965 INFO    WriterThread:22596 [datastore.py:close():257] close: wandb\run-20201108_141603-2vl3irn6\run-2vl3irn6.wandb
2020-11-08 14:16:05,965 INFO    HandlerThread:22596 [handler.py:finish():271] shutting down handler
2020-11-08 14:16:06,074 ERROR   MainThread:22596 [internal.py:wandb_internal():129] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 33, in run
    self._run()
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 60, in _run
    self._process(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal.py", line 233, in _process
    self._sm.send(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 92, in send
    send_handler(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 564, in send_config
    config_util.save_config_file_from_dict(config_path, config_dict)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\lib\config_util.py", line 48, in save_config_file_from_dict
    conf_file.write(data)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2581' in position 388: character maps to <undefined>
2020-11-08 14:16:06,102 DEBUG   raven-sentry.BackgroundWorker:22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2020-11-08 14:16:06,322 DEBUG   raven-sentry.BackgroundWorker:22596 [connectionpool.py:_make_request():433] https://o151352.ingest.sentry.io:443 "POST /api/5288891/store/ HTTP/1.1" 200 41
2020-11-08 14:16:06,905 DEBUG   Thread-9  :22596 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:16:07,160 DEBUG   Thread-9  :22596 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /files/submalpast/ch-en-try/2vl3irn6/file_stream HTTP/1.1" 200 None
2020-11-08 14:16:08,114 INFO    MainThread:22596 [internal.py:handle_exit():138] Internal process exited
