2020-11-08 14:25:59,411 INFO    MainThread:20120 [internal.py:wandb_internal():63] W&B internal server running at pid: 20120
2020-11-08 14:25:59,413 DEBUG   HandlerThread:20120 [handler.py:handle_request():55] handle_request: check_version
2020-11-08 14:25:59,413 INFO    WriterThread:20120 [datastore.py:open_for_write():76] open: wandb\run-20201108_142558-1vmc4si1\run-1vmc4si1.wandb
2020-11-08 14:25:59,414 DEBUG   SenderThread:20120 [sender.py:send():90] send: header
2020-11-08 14:25:59,414 DEBUG   SenderThread:20120 [sender.py:send():90] send: request
2020-11-08 14:25:59,414 DEBUG   SenderThread:20120 [sender.py:send_request():99] send_request: check_version
2020-11-08 14:25:59,420 DEBUG   Thread-8  :20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): pypi.org:443
2020-11-08 14:25:59,508 DEBUG   Thread-8  :20120 [connectionpool.py:_make_request():433] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51383
2020-11-08 14:25:59,552 DEBUG   SenderThread:20120 [sender.py:send():90] send: run
2020-11-08 14:25:59,555 INFO    SenderThread:20120 [sender.py:_maybe_setup_resume():280] checking resume status for None/ch-en-try/1vmc4si1
2020-11-08 14:25:59,560 DEBUG   SenderThread:20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:25:59,691 DEBUG   SenderThread:20120 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:25:59,701 DEBUG   SenderThread:20120 [util.py:is_cygwin_git():315] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2020-11-08 14:25:59,703 DEBUG   SenderThread:20120 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:25:59,764 DEBUG   SenderThread:20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:25:59,926 DEBUG   SenderThread:20120 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:25:59,971 DEBUG   HandlerThread:20120 [handler.py:handle_request():55] handle_request: run_start
2020-11-08 14:25:59,974 INFO    SenderThread:20120 [dir_watcher.py:__init__():164] watching files in: wandb\run-20201108_142558-1vmc4si1\files
2020-11-08 14:25:59,974 INFO    SenderThread:20120 [sender.py:_start_run_threads():487] run started: 1vmc4si1 with start time 1604863558
2020-11-08 14:25:59,974 DEBUG   SenderThread:20120 [sender.py:send():90] send: summary
2020-11-08 14:25:59,975 INFO    SenderThread:20120 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2020-11-08 14:26:00,000 DEBUG   HandlerThread:20120 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:26:00,059 DEBUG   HandlerThread:20120 [cmd.py:execute():718] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=None)
2020-11-08 14:26:00,212 DEBUG   SenderThread:20120 [sender.py:send():90] send: files
2020-11-08 14:26:00,212 INFO    SenderThread:20120 [sender.py:_save_file():568] saving file wandb-metadata.json with policy now
2020-11-08 14:26:00,212 DEBUG   HandlerThread:20120 [handler.py:handle_request():55] handle_request: status
2020-11-08 14:26:00,213 DEBUG   SenderThread:20120 [sender.py:send():90] send: request
2020-11-08 14:26:00,213 DEBUG   SenderThread:20120 [sender.py:send_request():99] send_request: status
2020-11-08 14:26:00,216 DEBUG   SenderThread:20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:26:00,221 DEBUG   Thread-17 :20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:26:00,322 DEBUG   SenderThread:20120 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:26:00,324 DEBUG   SenderThread:20120 [sender.py:send():90] send: config
2020-11-08 14:26:00,328 DEBUG   SenderThread:20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:26:00,340 DEBUG   Thread-17 :20120 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:26:00,344 DEBUG   Thread-17 :20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-08 14:26:00,485 DEBUG   SenderThread:20120 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:26:00,603 DEBUG   HandlerThread:20120 [handler.py:handle_request():55] handle_request: pause
2020-11-08 14:26:00,603 INFO    HandlerThread:20120 [handler.py:handle_request_pause():226] stopping system metrics thread
2020-11-08 14:26:00,689 DEBUG   Thread-17 :20120 [connectionpool.py:_make_request():433] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/submalpast/ch-en-try/1vmc4si1/wandb-metadata.json?Expires=1604949960&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ShK5TDWrC3daIutc2Zo2yv1Tbwg4NPoRWms4Dezjcex7GmRxjHHvrbyS2JTa3WbMYfqqAnmwxIeD6lRvkH1NaIyl2Vh8i2SnNvQF83xNHmK%2FVSXXANxPcGKn8Wcz21jbL%2FV0RIE0R0SzEK%2BsDnRQQWDxUcDuYqVN8VVDjcO7z15xDRKnxtM6QuPc8gXNTQBDURw%2FlJwIG1F8OZswFJMBQYfklvYcyip7Ng8OZBLhCs7xnPGfqnEG7GiCA2l0akbjxKwGhvzu8aeLdHM9Bx04K3%2BPPCU7s1IsH%2FqzXeNCZ%2B2ARvV%2FP602kWtPVZcyC9djHTAXunmVBlgLGzsb7prtjQ%3D%3D HTTP/1.1" 200 0
2020-11-08 14:26:00,695 INFO    Thread-17 :20120 [upload_job.py:push():131] Uploaded file C:\Users\presu\AppData\Local\Temp\tmpooan8enhwandb\7i6eff2c-wandb-metadata.json
2020-11-08 14:26:00,737 INFO    HandlerThread:20120 [handler.py:finish():271] shutting down handler
2020-11-08 14:26:00,996 INFO    Thread-12 :20120 [dir_watcher.py:_on_file_modified():225] file/dir modified: wandb\run-20201108_142558-1vmc4si1\files\config.yaml
2020-11-08 14:26:00,997 INFO    Thread-12 :20120 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142558-1vmc4si1\files\output.log
2020-11-08 14:26:00,997 INFO    Thread-12 :20120 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142558-1vmc4si1\files\wandb-metadata.json
2020-11-08 14:26:00,997 INFO    Thread-12 :20120 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142558-1vmc4si1\files\requirements.txt
2020-11-08 14:26:00,998 INFO    Thread-12 :20120 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142558-1vmc4si1\files\wandb-summary.json
2020-11-08 14:26:01,237 INFO    WriterThread:20120 [datastore.py:close():257] close: wandb\run-20201108_142558-1vmc4si1\run-1vmc4si1.wandb
2020-11-08 14:26:01,424 ERROR   MainThread:20120 [internal.py:wandb_internal():129] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 33, in run
    self._run()
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 60, in _run
    self._process(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal.py", line 233, in _process
    self._sm.send(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 92, in send
    send_handler(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 564, in send_config
    config_util.save_config_file_from_dict(config_path, config_dict)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\lib\config_util.py", line 48, in save_config_file_from_dict
    conf_file.write(data)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2581' in position 388: character maps to <undefined>
2020-11-08 14:26:01,438 DEBUG   raven-sentry.BackgroundWorker:20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2020-11-08 14:26:01,620 DEBUG   raven-sentry.BackgroundWorker:20120 [connectionpool.py:_make_request():433] https://o151352.ingest.sentry.io:443 "POST /api/5288891/store/ HTTP/1.1" 200 41
2020-11-08 14:26:02,339 DEBUG   Thread-9  :20120 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:26:02,484 DEBUG   Thread-9  :20120 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /files/submalpast/ch-en-try/1vmc4si1/file_stream HTTP/1.1" 200 None
2020-11-08 14:26:03,443 INFO    MainThread:20120 [internal.py:handle_exit():138] Internal process exited
